### ISSUE TITLE
Further development ?

### ISSUE THREAD

**Issue by starkgate** [LennyPenny/openmw-simple-mod-manager#1]
Nice program you have here, very useful ! Do you plan on developping it further ?
A functionality I would love to see would be a GUI where you can drag mods to change the load order. Also, a way to see conflicts would be invaluable.
A bit like Mod Organizer (although I imagine Mod Organizer would be very complicated to replicate^^).

**Comment by LennyPenny** [comment]
I would much rather build all these features into the openmw launcher itself, but I have always had problems getting it to build on Windows. 

Right now just change the load order in the openmw launcher, this mod manager will preserve whatever you set there.

**Comment by LennyPenny** [comment]
I just added another little script to help merge leveled lists on windows - you use that in conjuction with tes3cmd to see all conflicts as well I think! 
Also I think the openmw launcher has all the functionality to easily order your scripts now.
